export const LOAD_BOOK_STATUSES_SUCCESS = 'LOAD_BOOK_STATUSES_SUCCESS';
export const FILTER_BOOKS = 'FILTER_BOOKS';
export const LOAD_FILTERED_BOOKS_SUCCESS = 'LOAD_FILTERED_BOOKS_SUCCESS';

export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOK_SUCCESS = 'LOAD_BOOK_SUCCESS';
export const BOOK_EDIT_MODE = 'BOOK_EDIT_MODE';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';


export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHOR_SUCCESS = 'LOAD_AUTHOR_SUCCESS';
export const FILTER_AUTHORS = 'FILTER_AUTHORS';
export const LOAD_FILTERED_AUTHORS_SUCCESS = 'LOAD_FILTERED_AUTHORS_SUCCESS';
export const AUTHOR_EDIT_MODE = 'AUTHOR_EDIT_MODE';
export const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';

export const LOAD_PUBLISHERS_SUCCESS = 'LOAD_PUBLISHERS_SUCCESS';
export const LOAD_PUBLISHER_SUCCESS = 'LOAD_PUBLISHER_SUCCESS';
export const FILTER_PUBLISHERS = 'FILTER_PUBLISHERS';
export const LOAD_FILTERED_PUBLISHERS_SUCCESS = 'LOAD_FILTERED_PUBLISHERS_SUCCESS';
export const PUBLISHER_EDIT_MODE = 'PUBLISHER_EDIT_MODE';
export const CREATE_PUBLISHER_SUCCESS = 'CREATE_PUBLISHER_SUCCESS';

export const FILTER_LOANS = 'FILTER_LOANS';
export const LOAD_FILTERED_LOANS_SUCCESS = 'LOAD_FILTERED_LOANS_SUCCESS';
export const LOAD_LOANS_SUCCESS = 'LOAD_LOANS_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const FILTER_USERS = 'FILTER_USERS';
export const LOAD_FILTERED_USERS_SUCCESS = 'LOAD_FILTERED_USERS_SUCCESS';
export const USER_EDIT_MODE = 'USER_EDIT_MODE';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOFF_SUCCESS = 'LOGOFF_SUCCESS';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';